### ISSUE TITLE
Plugin does not work with webpack 5

### ISSUE THREAD

**Issue by ogusti** [smooth-code/error-overlay-webpack-plugin#69] opened 2020-10-26 07:23 UTC
Everything works fine in `"webpack": "^4.1.3"`.
In `"webpack": "^5.1.3"` this error appears:

<img width="525" alt="Screen Shot 2020-10-26 at 10 19 04" src="https://user-images.githubusercontent.com/32015285/97144026-cdb88800-1774-11eb-820d-1e54f155fb37.png">

**Comment by gregberge** [comment] 2020-10-28 06:58
Not a surprise! I will not fix it on my own, if someone is interested, feel free to submit a PR.

**Comment by gregberge** [comment] 2020-10-28 07:00
Duplicate of #67

**Closed by gregberge** 2020-10-28 07:00 UTC
Labels: enhancement
