### ISSUE TITLE
Not seeing error overlay

### ISSUE THREAD

**Issue by kimsagro1** [smooth-code/error-overlay-webpack-plugin#8] opened 2018-03-12 03:27 UTC
Given the following files

`package.json`

```json
"devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "babel-loader": "8.0.0-beta.0",
    "error-overlay-webpack-plugin": "^0.1.3",
    "html-webpack-plugin": "^3.0.6",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.11",
    "webpack-dev-server": "^3.1.1"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
```

`webpack.config.js`

```javascript
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin')

module.exports = {
    mode: 'development',
    entry: ['./src/index.js'],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env', '@babel/preset-react'],
                    },
                },
            },
        ],
    },
    plugins: [
        new ErrorOverlayPlugin(),

        new webpack.HotModuleReplacementPlugin(),

        new HtmlWebpackPlugin({
            template: './src/index.html',
        }),
    ],
    devServer: {
        hot: true,
        open: true,
    },
}
```

`index.js`

```javascript
import React from 'react'
import ReactDOM from 'react-dom'

ReactDOM.render(
    <h1>{this.should.show.overlay}</h1>,
    document.getElementById('root'),
)

if (module.hot) module.hot.accept()
```

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body><div id="root"></div></body>
</html>
```

Running `yarn webpack-dev-server`

results in a console error, but no overlay

```
Uncaught TypeError: Cannot read property 'should' of undefined
    at eval (webpack:///./src/index.js?:9:76)
    at Object../src/index.js (http://localhost:8080/main.js:1383:1)
    at __webpack_require__ (http://localhost:8080/main.js:710:30)
    at fn (http://localhost:8080/main.js:95:20)
    at eval (webpack:///multi_./node_modules/error-overlay-webpack-plugin/lib/entry.js_(webpack)-dev-server/client?:4:18)
    at Object.0 (http://localhost:8080/main.js:1394:1)
    at __webpack_require__ (http://localhost:8080/main.js:710:30)
    at http://localhost:8080/main.js:762:37
    at http://localhost:8080/main.js:765:10
```

**Comment by alextrastero** [comment] 2018-03-12 10:11
Pasting my config incase I have some incompatible plugins:
```js
  devtool: 'source-map',
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.IgnorePlugin(/webpack-stats\.json$/),
    new webpack.EnvironmentPlugin(['XXX']),
    new webpack.DefinePlugin({
      __DEVELOPMENT__: true,
      __DEVTOOLS__: true
    }),
    new webpack.IgnorePlugin(/^buffer|crypto|fs$/, /analyserLib\.js/),
    new ErrorOverlayPlugin(),
    new HtmlWebpackPlugin({
      template: 'index.html.ejs'
    })
  ],
  devServer: {
    hot: false,
    inline: true,
    port: PORT,
    historyApiFallback: true,
    stats: { colors: true }
  }
```

**Comment by hipstersmoothie** [comment] 2018-03-12 19:47
I seem to not be able to set 'mode'. is this a webpack 4 option?

**Comment by kimsagro1** [comment] 2018-03-13 22:01
@hipstersmoothie yep, see https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a

**Comment by neoziro** [comment] 2018-03-13 22:26
`HtmlWebpackPlugin` is probably the source of the problem, can you confirm it?

**Comment by kimsagro1** [comment] 2018-03-14 02:06
Removing `HtmlWebpackPlugin` had no effect

**Comment by michaelkoelewijn** [comment] 2018-03-15 15:32
Same problem on Webpack 3
`var Webpack = require('webpack');
var Config = require('webpack-config').default;
var ExtractTextPlugin  = require('extract-text-webpack-plugin');
var ErrorOverlayPlugin = require('error-overlay-webpack-plugin');
module.exports = new Config().extend('./webpack.config.base.js').merge({
    devtool: "source-map",
    output: {
        filename: '[name].js'
    },
    plugins: [
        new ErrorOverlayPlugin(),
        new Webpack.LoaderOptionsPlugin({
            minimize: false,
            debug: true,
        }),
        new ExtractTextPlugin({
            filename: 'main.css',
            allChunks: true,
        }),
    ]
});
`

**Comment by emzero** [comment] 2018-04-02 23:20
I can confirm this too. Not seeing the overlay.
Webpack 4.4.1
React 16.3.0

```javascript
const HtmlWebPackPlugin = require("html-webpack-plugin");
const ErrorOverlayPlugin = require("error-overlay-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      },
      {
        test: /\.css$/,
        use: [{ loader: "style-loader" }, { loader: "css-loader" }]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin(
      {
        template: "./src/index.html",
        filename: "./index.html"
      },
      new ErrorOverlayPlugin()
    )
  ]
};
```

**Comment by neoziro** [comment] 2018-04-03 20:44
@emzero where are your `entry` in your config?

**Comment by emzero** [comment] 2018-04-03 20:48
@neoziro Using webpack 4 defaults (`./src`).

**Comment by neoziro** [comment] 2018-04-03 20:49
@emzero can you try to specify it and see if it is the source of your problem?

**Comment by emzero** [comment] 2018-04-03 20:53
Nope, same thing.

![image](https://user-images.githubusercontent.com/412489/38275337-ef795f90-3767-11e8-9eab-46df988ca6e5.png)

**Comment by willwull** [comment] 2018-04-15 12:55
Anyone got this working yet? Still not working for me @neoziro

**Comment by neoziro** [comment] 2018-04-15 17:47
Just set it up on another project and it works. It takes some time to display but still works.

**Comment by neoziro** [comment] 2018-04-15 17:48
@emzero it must be `HtmlWebpackPlugin` the source of the problem.

**Comment by neoziro** [comment] 2018-04-24 12:50
I don't have time to investigate it, if you experience this issue I will be glad if you could debug it to try what's going on. On my side, I use this plugin and it works but I do not use `HtmlWebpackPlugin`.

**Comment by msteward** [comment] 2018-05-09 18:35
I started having this "issue" when using ErrorBoundaries with React 16. React is handling the error now so I suspect it never makes it to the error overlay. If you're using ErrorBoundaries I suspect you'll need to handle this yourself and display some sort of error on the screen with the component stack trace when in development mode.

**Comment by neoziro** [comment] 2018-05-10 16:48
@msteward yes I think you are right, this plugin only catch uncaught exceptions. So if you use a ErrorBoundary, you should throw back the error to trigger the overlay.

**Comment by gpbl** [comment] 2018-05-14 08:54
> So if you use a ErrorBoundary, you should throw back the error to trigger the overlay.

I'm having a similar issue and I wonder where is the right place where to throw the error back? I tought to `throw` it from the ErrorBoundary component but clearly it doesn't work.

**Comment by neoziro** [comment] 2018-05-17 09:49
I can't reproduce it, if someone provide a real not working example I could take a look.

**Comment by neoziro** [comment] 2018-05-25 15:08
I think it was a browser relative issue, I hop it will be fixed by #15. Feel free to open a new issue if you experience the problem again.

**Closed by neoziro** 2018-05-25 15:08 UTC

**Comment by siddharthkp** [comment] 2018-07-11 09:13
Can we open this issue again?

Can't get it to work with `webpack@4.15.1` + `webpack-dev-server@3.1.4`

**Comment by foisonocean** [comment] 2018-07-13 05:32
@neoziro 
After change my webpack devtool to `cheap-module-source-map`, I got this error:
![image](https://user-images.githubusercontent.com/15059605/42674148-158ac20e-86a1-11e8-8aa5-b918b558f794.png)

**Comment by alextrastero** [comment] 2018-07-13 09:59
This setup works for me FYI
```js
const path = require('path');
const webpack = require('webpack');
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin')

module.exports = {
  mode: 'development',
  entry: './index.js',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  devtool: 'cheap-module-source-map,
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['@babel/react', '@babel/preset-env']
        }
      }
    ]
  },
  plugins: [new ErrorOverlayPlugin()]
};
```

**Comment by ioanungurean** [comment] 2018-08-27 00:26
@siddharthkp thank you, I was struggling for a while now and I could not understand why it's not working.

**Comment by bitwhys** [comment] 2018-09-10 03:56
@siddharthkp that worked for me as well. Thank you (fyi webpack @4.17.2)

**Comment by SkymanOne** [comment] 2021-08-01 22:31
> @neoziro
> After change my webpack devtool to `cheap-module-source-map`, I got this error:
> ![image](https://user-images.githubusercontent.com/15059605/42674148-158ac20e-86a1-11e8-8aa5-b918b558f794.png)

I still have the same issue with webpack 4 and react. Have you managed to fix it?

**Comment by joshgoebel** [comment] 2022-02-01 21:06
> This setup works for me FYI

Where is this file you're changing?  I'm having this same problem with React 17 with a freshly created app with react-create-app and it's driving me nuts... but the project doesn't really have much in the way of configs other than `package.json`, I assume it's all hidden deep inside react-scripts or some such.

**Comment by alextrastero** [comment] 2022-02-02 10:17
> > This setup works for me FYI
> 
> Where is this file you're changing? I'm having this same problem with React 17 with a freshly created app with react-create-app and it's driving me nuts... but the project doesn't really have much in the way of configs other than `package.json`, I assume it's all hidden deep inside react-scripts or some such.

@joshgoebel my message is from 2018. AFAIK with create-react-app you would need to eject in order to have a custom webpack config, actually with create-react-app you don't need this webpack plugin... 🤔

**Comment by joshgoebel** [comment] 2022-02-02 18:08
It seems the error reporting is still there, it's just been changed to support fewer cases that before (now they instead log to console)... I found another issue where people are discussion the merits of the change since it seems like a step backwards in some ways vs what we had prior.
